// Stub routes file for testing purposes
// In production, this would be generated by rails routes or js-routes gem

export default {
  // Add minimal route stubs for compilation
  root_path: () => '/',
  root_url: () => '/',
  dashboard_path: () => '/dashboard',
  // Add other routes as needed for compilation
};